@script = <<EOF
  sudo yum update -y
  sudo yum install -y wget ntp openssl-devel
  sudo ntpdate ntp.nict.jp
  (cd /tmp && wget https://packages.chef.io/stable/el/6/chef-server-core-12.5.0-1.el6.x86_64.rpm)
  sudo rpm -Uvh /tmp/chef-server-core-12.0.1-1.x86_64.rpm
EOF

@client_script = <<EOF
  sudo yum update -y
  sudo yum install -y ntp openssl-devel
  sudo ntpdate ntp.nict.jp
  curl -L https://www.chef.io/chef/install.sh | sudo bash
  sudo bash -c "echo '192.168.33.12 chef-server' >> /etc/hosts"
EOF

Vagrant.configure('2') do |config|
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--memory', '1024']
  end

  config.vm.define :chef_server do |host|
    host.vm.box = 'opscode_centos-6.5'
    host.vm.box = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box'
    host.vm.hostname = 'chef-server'
    host.vm.network :private_network, ip: '192.168.33.12'
    host.vm.provision :shell, inline: @script
  end

  config.vm.define :my_node do |host|
    host.vm.box = 'opscode_centos-6.5'
    host.vm.box = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box'
    host.vm.hostname = 'my-node'
    host.vm.network :private_network, ip: '192.168.33.13'
    host.vm.provision :shell, inline: @client_script
  end
end
