@server_script = <<EOF
  (cd /tmp && wget https://packages.chef.io/stable/ubuntu/14.04/chef-server-core_12.6.0-1_amd64.deb)
  sudo dpkg -i /tmp/chef-server-core_12.6.0-1_amd64.deb
  sudo cp /opt/opscode/embedded/service/omnibus-ctl/spec/fixtures/pivotal.pem \
  /etc/opscode
  chef-server-ctl reconfigure
EOF

@client_script = <<EOF
  curl -L https://www.chef.io/chef/install.sh | sudo bash
  sudo bash -c "echo '192.168.33.12 chef-server' >> /etc/hosts"
EOF

Vagrant.configure('2') do |config|
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--memory', '2048']
  end

  config.vm.define :chef_server do |host|
    host.vm.box = 'ubuntu/trusty64'
    host.vm.hostname = 'chef-server'
    host.vm.network :private_network, ip: '192.168.33.12'
    host.vm.provision :shell, inline: @server_script
  end

  config.vm.define :my_node do |host|
    host.vm.box = 'ubuntu/trusty64'
    host.vm.hostname = 'my-node'
    host.vm.network :private_network, ip: '192.168.33.13'
    host.vm.provision :shell, inline: @client_script
  end
end
